# Markov Transition Probabilities

In [6]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [27]:
def transition_matrix_pandas(x):
    s = pd.Series(list(x))
    pairs = pd.crosstab(s.shift(1).dropna(), s[1:])

    states = sorted(set(s))
    pairs = pairs.reindex(index=states, columns=states, fill_value=0)

    T = pairs.div(pairs.sum(axis=1), axis=0).rename_axis('t-1').rename_axis('t', axis=1)
    return T, states

In [30]:
x = [0, 1, 1]
T, states = transition_matrix_pandas(x)
T

t      0    1
t-1
0    0.0  1.0
1    0.0  1.0

In [34]:
x = [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
     0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
     1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     ]
T, states = transition_matrix_pandas(x)
T

t           0         1
t-1
0    0.911111  0.088889
1    0.421053  0.578947

In [35]:
s = pd.Series(list(x))
pairs = pd.crosstab(s.shift(1).dropna(), s[1:])

In [40]:
s.shift(1).dropna()

1      0.0
2      0.0
3      0.0
4      0.0
5      0.0
      ...
105    0.0
106    0.0
107    0.0
108    0.0
109    0.0
Length: 109, dtype: float64

In [36]:
pairs

col_0   0   1
row_0
0.0    82   8
1.0     8  11